### ISSUE TITLE
Again: comments that are placed "by accident"

### ISSUE THREAD

**Issue by tammoterhark** [PlanBCode/hypha#106]
From De Stadsbron:

Dag Tammo,

Iemand van De Golfbreker heeft abusievelijk een mail aan mij onder mijn laatste verhaal op de Stadsbron geplakt. Zelf kan ze het niet meer weghalen. Kan jij dat?

Groet,
Arjeh
--------------
http://destadsbron.nl/nl/Beetje_hoop_voor_het_joodse_monument

But also for comment spam: how to moderate/delete comments?

For now: please help by deleting this comment.

**Comment by matthijskooijman** [comment]
This is a duplcate of #101, so I'm closing it.

Note that there's two parts to this issue:
 - Emphasizing the need to have moderation, which would have been better as a comment on #101, or perhaps not mentioned at all.
 - A request to remove a single thing from the Stadsbron hypha instance. This I think has no place on this github at all, since this github is about developing the hypha software, not about maintaining that particular instance. That request would have been better been sent by e-mail. Nevertheless, I went ahead and removed the particular comment now.

**Comment by tammoterhark** [comment]
Thank you! ;-)
