### ISSUE TITLE
Missing installation instructions

### ISSUE THREAD

**Issue by tammoterhark** [PlanBCode/hypha#11]
I would very much like to see a short installation instruction, just to toy around with the Github version.

**Comment by tammoterhark** [comment]
It is getting serious:

> serious error: missing system file hypha.xml

**Comment by matthijskooijman** [comment]
From the top of my head, installation should be simple:
 - Make a clone of the repository somewhere in your webserver's document root
 - Make sure that either the directory itself and all contents are writable by PHP (alternatively, make just the directory itself, the data directory and the system directory writable).
 - Navigate to `hypha.php` to run the installer. You will be asked for a login, which is stored at the top of `hypha.php`. The default is an empty username and password.

Afterwards, you should be able to remove write permissions from all files, except for the data directory.

Care to try these instructions and see if they work? If so, I'll add them to the README.

One alternative is that, from a running hypha instance, you can also navigate to `hypha.php` to build a downloadable bundle of the installed hypha, which can unpack itself onto another system. I haven't tested this in a while, but I think it should still work.

**Comment by tammoterhark** [comment]
Tried it, but no luck: hypha.php promts me for a name of the superuser, a password and some questions about modules and languages. After that I clicked on "build".

Downloaded hypha.php and placed in in the root. (Strange: this will make the GIT confused: now hypha.php will contain settings?)

I then went to localhost.hypha.nl but error 500.

**Comment by tammoterhark** [comment]
Still one thing missing: when installed on Windows/Xampp editor does not show. Harmen said there needs to be some change in php.ini, but I would like to know what change that would be.

**Comment by matthijskooijman** [comment]
> Tried it, but no luck: hypha.php promts me for a name of the superuser, a password and some questions about modules and languages. After that I clicked on "build".

Hm, that's the interface you should get after you succesfully installed hypha already (it allows building a new hypha.php bundle to copy to another server). This is only displayed if [a `data/hypha.xml` exists](https://github.com/PlanBCode/hypha/blob/master/hypha.php#L547), so perhaps you still had that file from an earlier failed attempt?

> Still one thing missing: when installed on Windows/Xampp editor does not show. Harmen said there needs to be some change in php.ini, but I would like to know what change that would be.

Ah, I suspect this is needed to allow hypha.php to download wymeditor. This happens in two stages:
 -First it [downloads some metadata from github](https://github.com/PlanBCode/hypha/blob/master/hypha.php#L406-L410). This uses curl, so it needs the curl support (which might be an extension to separately install)?
 - Secondly, it [downloads the actual wymeditor file](https://github.com/PlanBCode/hypha/blob/master/hypha.php#L413). This uses file_get_contents with a HTTP url, which needs fopen wrappers to be enabled. This is done using [`allow_url_fopen`](http://php.net/manual/en/filesystem.configuration.php#ini.allow-url-fopen) in php.ini.

Looking at the code now, it seems weird to use curl for one and fopen wrappers for the other. I suspect that curl is used because some options are needed, though it now only sets the user agent (which I don't think should matter for github), `CURLOPT_RETURNTRANSFER` is just an option to return the result instead of outputting it.

I wonder if it wouldn't be better to use either curl, or fopen wrappers in both cases. I think fopen wrappers are often disabled for security reasons, and using curl is more explicit that it does a HTTP request, so curl is probably better here. @laurensmartina, what's your experience in this regard?

**Comment by tammoterhark** [comment]
From my php.ini:

`allow_url_fopen = On`

**Comment by tammoterhark** [comment]
and:

`allow_url_include = Off`

**Comment by tammoterhark** [comment]
@matthijskooijman Yes, I had a .xml from a previous attempt. I deleted it and it worked. i should have mentioned that here.

**Comment by matthijskooijman** [comment]
Then perhaps it's the curl support that's missing, not sure how that works on Windows... Or perhaps my suggestions are wrong and it's not the installation that fails but there is some browser-side error. I'm wondering if hypha.php should have shown errors, or aborted, when this failed (perhaps only in the Apache error log?).

Do you have any files in the `system/wymeditor` directory? If not, then it is indeed the installation that failed.

**Comment by tammoterhark** [comment]
Even better: there is no directory called /system/wymeditor...

**Comment by tammoterhark** [comment]
There neither is one here:
https://github.com/PlanBCode/hypha/tree/master/system
Would it not be easier to just place it there?

**Comment by matthijskooijman** [comment]
The idea is that the installer always fetches the latest version of wymeditor, which is nice, but also has downsides (incompatible changes can break it, and apparently curl/fopen support isn't always working automatically). @giplt, do you have any strong arguments for autodownloading?

**Comment by giplt** [comment]
**pro**
- benefit from latest patches with respect to stability, security, speed and platform support
- small download size for only hypha's core, which acts as a seed that can pull in whatever it needs in external dependencies
**con**
- risk of breaking hypha with incompatible changes
- not fully self contained, i.e. internet connection required for installation

**Comment by matthijskooijman** [comment]
We looked more closely, it turns out that @tammoterhark's Windows/XAMPP version does not support HTTPS urls in curl (perhaps missing or old certificates). This does not give any curl errors in error log, though.

After manually installing wymeditor, its icons did not work. Turns out that the static file serving uses `finfo_file()` which was disabled on @tammoterhark's XAMPP installation. Enabling it required adding (uncommenting) this line in php.php:

    extension=php_fileinfo.dll

Maybe hypha.php should check for this extension on install?

**Comment by giplt** [comment]
Installation instruction can now be found both on www.hypha.net and in README.md in the GitHub repo.
The first describes a method to clone from an existing hypha instance, yielding a self-extracting install script to deploy on another server.
The latter describes a way to pull a clone from GitHub.
Platform specific instructions for setting up a proper environment under Linux, Windows or MacOS will be added to www.hypha.net. Please send your suggestions, solved problems or fully tested instructions to info [at] hypha [dot] net.
