### ISSUE TITLE
change "name" label to "page title" or "article title" in make new page window

### ISSUE THREAD

**Issue by dianawi** [PlanBCode/hypha#111]
solution: change label 'name' to 'page name'

**Comment by tammoterhark** [comment]
related to: https://github.com/PlanBCode/hypha/issues/78

We have to fix that first: page name and page title are dirrent fields, both with their own purpose:
page name: identifier in inner workings of hypha
page title: that what is displayed for reader

Currently page title and page name are identical at page creation, page title can be changed afterwards. page name cannot be changed.

**Comment by matthijskooijman** [comment]
The confusion is that users do not understand the concept of "Page name", and tend to fill in their own name or otherwise get confused. Finding a better label could help here (though perhaps it should not be "title", since an article has both a name and a title. OTOH, the name you fill in is also the default for the title, I believe).

Note that this issue might be a bit confusing for developers, since the name/title distinction only exists for articles, other page types only have a name which determins both the URL, the index entry and the displayed page title. I think adding this distinction to other type (and making it more clear for articles) is the subject of #78.
