### ISSUE TITLE
Converge to one coding style for datatypes

### ISSUE THREAD

**Issue by giplt** [PlanBCode/hypha#135]
Various datatypes (web page, article, festival) now have different coding styles. We need to compare these and make a choice for some preferred way of implementing a new module.

Things to keep in mind:
- balance between flexibility and clarity in structures for data flow and processing commands
- comprehensibility of code at first reading to novice coders
- decide on mandatory methods:
  - a default pageview
  - a digest hook
  - notifications
  - code for automated testing
  - index view
  - a search hook

**Comment by laurensmartina** [comment]
https://github.com/PlanBCode/hypha/blob/newtext/system/datatypes/text.php is a suggestion for a new structure

**Comment by matthijskooijman** [comment]
This refactor is tracked in parts:
 - For textpage, this is already merged.
 - For article, this is in #258 
 - For mailinglist, Laurens is working on this
 - For festival, Matthijs will work on this

After all datatypes are completed, some additional refactoring can be done to make sure that instead of one global `<form>` tag, there will be one for each form separately.

**Comment by matthijskooijman** [comment]
After this is complete, I would also like to see #264 done.

**Comment by matthijskooijman** [comment]
Text, mailinglist and article have now been converted. Festival is in progress at #337. The settings special datatype should probably also be converted to allow #264 to be done.
