### ISSUE TITLE
Comment structure

### ISSUE THREAD

**Issue by tammoterhark** [PlanBCode/hypha#199]
See image. Discussion needed. The first that comes to mind is that the difference between a comment on the article and a comment on a comment is too little.

![de stadsbron test 3](https://user-images.githubusercontent.com/6483317/51836821-d3fca480-2301-11e9-964a-cd6bcce51979.png)

Possible directions for solution:
- Comment on article should be called: "Comment on the article" (same as now)
- Comment on the previous comment could be called: "Add to dialogue" or something similar, to indicate that this is within a conversation.
- a comment on the article has another  status than a comment on the comment (status = class?)
- styling should better indicate difference between the two, html to be designed
- will we allow threaded comments? How many levels?

Furthermore
- a comment or an answers by the original author of the article could have another class, to indicate that the author "speaks"

**Comment by matthijskooijman** [comment]
I believe that #149 and and #177 by Bert already covers a small part of this. I'll see what part of that we can reuse from that and what needs to be different.

**Comment by matthijskooijman** [comment]
> will we allow threaded comments? How many levels?

There is only a first comment in each dissussions and replies in the discussion, there is no further nesting (and I think there should not be, otherwise things become a lot more complicated).

> a comment on the article has another status than a comment on the comment (status = class?)

I believe this is already possible, the first comment has a "first-comment" CSS class.


In #149, Bert improved the rendering of closed discussions, which seems good to discuss here too. He added a label in the top right, and also used the (already existing) `closed` CSS class to render closed discussions in a different background color.

Here's what's present now:

![image](https://user-images.githubusercontent.com/194491/52088618-ac7d3480-25ac-11e9-965a-5052082b1b85.png)

@tammoterhark, how does that look?

**Comment by matthijskooijman** [comment]
@tammoterhark, I think most of this is now implemented, except the author-speaks CSS class. Could you double-check and create separate new issues for anything that is yet to be implemented?

**Comment by matthijskooijman** [comment]
Since most of this is implemented, and the remaining "author speaks" is not quite trivial, I'm closing this. If the wish for this feature comes up again, we can create a new issue.
