### ISSUE TITLE
Comment on comment failure: resubmit name and email

### ISSUE THREAD

**Issue by tammoterhark** [PlanBCode/hypha#200]
When you leave a correctly filled in comment form on a comment and click on submit, you are shown an error and have to re-submit the name and email address.

![de stadsbron test 4](https://user-images.githubusercontent.com/6483317/51837365-7bc6a200-2303-11e9-9ead-a86266382c2c.png)

![de stadsbron test 5](https://user-images.githubusercontent.com/6483317/51837375-808b5600-2303-11e9-97ef-14591b270257.png)

**Comment by matthijskooijman** [comment]
I dug into this a little and found that this is caused because on an article page there typically are a bunch of "add public comment" forms (some of which are for replies, and one is for new comments). Since all these live in a single HTML form tag, all of them get posted at the same time.

For the "comment text" fields, these fields are made unique by adding e.g. /id1234  to the name of the field (using the id of the discussion). However, the name and e-mail field are not treated like this, so all these fields are named identically (so the fields in the last "start new discussion" form overwrite the values of all others, typically with the empty value).

A simple fix seems to be to just add the same /id1234 suffix to the name and e-mail field names, but these fields are handled in the more generate `createDiscussionComent` method, which does not have easy access to the id (and must handle both with and without suffix). I actually think that it is a bit weird that the validation happens in the caller of `createDiscussionComment`, whereas the handling happens inside that method, since that leads to potential mismatch of field names. I suspect some refactoring might be needed here.

As for the trick of adding a suffix, this is of course not ideal as implemented now. I guess it could be better to actually use a different HTML form tag for each form (which deviates a bit from the style in the rest of the project), or perhaps letting such a suffix (or prefix) be handled inside the form class (so you assign a unique prefix to the form class, which then handles putting it on the generated HTML as well as stripping it from the received POST data, so you effectively create virtually isolated forms).

@laurensmartina, any thoughts?
