### ISSUE TITLE
Store publication date in each new page/article/instance of content type

### ISSUE THREAD

**Issue by tammoterhark** [PlanBCode/hypha#268]
We need the publication date for:

- sorting the list of pages/articles
- automatically showing the publication date on the article page
- possibly some other purposes.

Maybe also store most recent edit date?

**Comment by matthijskooijman** [comment]
This is probably not too much work, but does interact with #258, so we can implement this as soon as that PR is merged.

**Comment by matthijskooijman** [comment]
For articles, the publication and edit date is now stored (#278). For textpages, the edit date is stored, a publication date does not make complete sense there (could be the date when a page was no longer private, maybe). For other types (e.g. mailinglist, festival) I'm not quite sure what these would mean at all.

For sorting, the tag index (#301) uses the publication date when available (articles) and edit date otherwise (textpages), which works well enough for now.

There might be some more work to be done here, but I think the initial task of this issue was completed, so I'm going to close it.
