### ISSUE TITLE
Create possibility to use Matomo analytics

### ISSUE THREAD

**Issue by tammoterhark** [PlanBCode/hypha#286]
Previously known as Piwik.
https://matomo.org/

Possible solution that also opens possibility to add other scripts for more flexibility:
https://knowledge.hubspot.com/cos-general/how-can-i-add-code-snippets-to-the-head-and-footer-html-of-my-pages

**Comment by matthijskooijman** [comment]
Is this not already possible by installing Matamo and then including the necessary snippet in `hypha.html`? I haven't looked at Matamo, but IIRC this is how you could use Piwik.

**Comment by tammoterhark** [comment]
I created a Matomo account on the servers of Tools for Research and added the necessary code to the head in hypha.html, but unfortunately this seems to be filtered out.

**Comment by tammoterhark** [comment]
Please see the remaining comments in the head at destadsbron.nl

**Comment by tammoterhark** [comment]
I do not understand how this works, but in the backend of Matomo I can see visotors hitting the website of De Stadsbron... Strange. Seems to work though...

**Comment by giplt** [comment]
Functional code is retained but can be found higher up in the page code. This is because hypha takes the hypha.html as a template and has various processes stuffing it with content and supporting javascript code before sending the result to the client. In the process it generates some 'well formatted' head with <meta> tags first, and <script> tags later. The Matomo remarks apparently are left last.

**Comment by tammoterhark** [comment]
Works now as hoped for.
