### ISSUE TITLE
Confusing names of fields in comments

### ISSUE THREAD

**Issue by tammoterhark** [PlanBCode/hypha#77]
- voorstel gemaakt en gecodeerd, wacht op akkoord.
- titel aan de discussie toevoegen i.p.v. nummer.
- Voorbeeld uitgewerkt 
- Discussie titel/onderwerp eigen style class = comment_subject gegeven. De stijl is aan te passen via settings.

**Comment by matthijskooijman** [comment]
Tammo will review this issue to figure out what needs to happen :-)

**Comment by tammoterhark** [comment]
This is now in https://github.com/PlanBCode/hypha/pull/149, but needs some attention.

**Comment by matthijskooijman** [comment]
After merging #149, we should check if #42 is also fixed.

**Comment by matthijskooijman** [comment]
I'm going to close this, since I think we decided not to add any title to a discussion (the first comment is the title of the discussion, in a way). Also, recent improvements to the comment styling probably already makes a more clear distinction between different threads. Feel free to reopen if this needs to be reconsidered.
