### ISSUE TITLE
No styling after merge

### ISSUE THREAD

**Issue by tammoterhark** [PlanBCode/hypha#95]
![image](https://user-images.githubusercontent.com/6483317/47666369-a9d10480-dba3-11e8-80fb-4f53da060cbc.png)

Maybe something to do with:

`<base href="http://localhost.hypha.nl%5C/">`

All links result in error 500

**Comment by tammoterhark** [comment]
Result on screen:
```
/test.php
\
/foo/bar
localhost.hypha.nl
```

**Comment by matthijskooijman** [comment]
Ah, seems that dirname returns `\` when it would otherwise return an empty string. I looked around the PHP sources, and found the relevant lines here: https://github.com/php/php-src/blob/40979277c0bf17d83272e42ffb26c3c0dc38f913/win32/ioutil.c#L555

I created #97 (from the fix-windows-rooturl branch), could you see if that fixes this? If so, feel free to merge that PR yourself :-)

The
